/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_pair01.h"
#include "Pin_pair01_aliases.h"
#include "Pin_PairLine1.h"
#include "Pin_PairLine1_aliases.h"
#include "Clock_1.h"
#include "PWM_1.h"
#include "Pin_pair03.h"
#include "Pin_pair03_aliases.h"
#include "PWM_3.h"
#include "Pin_PairLine3.h"
#include "Pin_PairLine3_aliases.h"
#include "Pin_RED.h"
#include "Pin_RED_aliases.h"
#include "Clock_2.h"
#include "PWM_2.h"
#include "Pin_PairLine2.h"
#include "Pin_PairLine2_aliases.h"
#include "Pin_pair02.h"
#include "Pin_pair02_aliases.h"
#include "Pin_SW2_int.h"
#include "Pin_PairLine4.h"
#include "Pin_PairLine4_aliases.h"
#include "Pin_SW2.h"
#include "Pin_SW2_aliases.h"
#include "Pin_pair04.h"
#include "Pin_pair04_aliases.h"
#include "Clock_3.h"
#include "Clock_4.h"
#include "PWM_4.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

